# Generated by Django 4.2 on 2024-08-17 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_employer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("salary", models.PositiveIntegerField()),
                (
                    "time_type",
                    models.CharField(
                        choices=[
                            ("FT", "Full time"),
                            ("PT", "Part time"),
                            ("HR", "Hourly"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "seniority",
                    models.CharField(
                        choices=[
                            ("IN", "Intern"),
                            ("JR", "Junior"),
                            ("MD", "Mid"),
                            ("SR", "Senior"),
                            ("LD", "Lead"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("EM", "Employment"),
                            ("PJ", "Project"),
                            ("IN", "Internship"),
                            ("SC", "Scholarship"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[("OS", "On site"), ("RM", "Remote"), ("HY", "Hybrid")],
                        max_length=2,
                    ),
                ),
                ("expire_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jobs.category",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.employer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PD", "Pending"),
                            ("AC", "Accepted"),
                            ("RJ", "Rejected"),
                        ],
                        max_length=2,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "resume",
                    models.FileField(upload_to=jobs.models.get_resume_upload_path),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.job"
                    ),
                ),
            ],
            options={
                "unique_together": {("job", "applicant")},
            },
        ),
    ]
