# Generated by Django 4.2 on 2024-08-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[("PD", "Pending"), ("AC", "Accepted"), ("RJ", "Rejected")],
                default="PD",
                max_length=2,
            ),
        ),
    ]
