# Generated by Django 4.2 on 2024-08-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_application_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
